const mongoose = require('mongoose')
const config = require('../config/config')
const userModel = require('./userModel')
const authModel = require('./authModel')
const contactModel = require('./contactModel')
const menuCategoryModel = require('./MenuCategory')
const customerModel = require('./customerModel')
const customerTokenModel = require('./customerTokenModel')
const db = {}
db.mongoose = mongoose;
db.mongodb = config.MONGO_DB;
db.userModel = userModel;
db.authModel = authModel;
db.contactModel = contactModel;
db.menuCategoryModel = menuCategoryModel;
db.customerModel = customerModel;
db.customerTokenModel = customerTokenModel
module.exports = db
